### ISSUE TITLE
LSVRC 2012 is not available at the provided link

### ISSUE THREAD

**Issue by marischu** [eembc/mlmark#14]
One of the evaluation datasets (LSVRC 2012) is no longer available at the link given. 

[https://image-net.org/challenges/LSVRC/2012/nonpub-downloads](https://image-net.org/challenges/LSVRC/2012/nonpub-downloads)

This link leads me to:
![image](https://user-images.githubusercontent.com/37053334/165179100-460eb255-95c2-4f5d-90d8-5356d178e3d6.png)

Having looked through the base website and manually navigated to where the dataset should be, it looks like this dataset may either be no longer hosted or there might be an issue on their side. 

Are there any other ways to acquire this dataset?

**Comment by petertorelli** [comment]
It appears this dataset is no longer publicly available. The only way to obtain it is to fill out an agreement with ImageNet that you will only use this data for research purposes:

https://www.image-net.org/download.php

**Comment by marischu** [comment]
That works, thank you so much!
