### ISSUE TITLE
What is the process for reporting issues with results?

### ISSUE THREAD

**Issue by psyhtest** [eembc/mlmark#2]
For example, the [currently available results on HiKey970](https://www.eembc.org/mlmark/view.php?benchmark_seq=13152,13151,13149,13148) list the GPU as Mali-G71, while it's [in fact](https://www.96boards.org/product/hikey970/) Mali-G72.

**Comment by petertorelli** [comment]
Thanks for pointing that out, it has been corrected. A link will be added to score page for reporting issues like this.
